import time
from selenium import webdriver
from selenium.webdriver.edge.service import Service
from selenium.webdriver.common.by import By

wd=webdriver.Edge()
wd.implicitly_wait(5)
wd.get('https://www.autopiano.cn/')

element=wd.find_element(By.CSS_SELECTOR,'div[class="piano-key-wrap d-flex flex-row justify-start align-start"]')

keys=element.find_elements(By.CSS_SELECTOR,'div[class="piano-key wkey key-hover"]')


def key_click(num):
    keys[num].find_element(By.CSS_SELECTOR,'div[class="keytip"]').click()
    

def key_click2(num1,num2):
    keys[num1].find_element(By.CSS_SELECTOR,'div[class="keytip"]').click()
    keys[num2].find_element(By.CSS_SELECTOR,'div[class="keytip"]').click()
    


time.sleep(1)
key_click(14)
time.sleep(0.3)
key_click(15)
time.sleep(0.6)
key_click2(16,10)
time.sleep(0.6)
key_click(18)
time.sleep(0.6)
key_click2(17,11)
time.sleep(0.6)
key_click(16)
time.sleep(0.6)
key_click2(15,9)
time.sleep(0.6)
key_click(14)
time.sleep(0.6)
keys[16].find_element(By.CSS_SELECTOR,'div[class="keytip"]').click()
keys[10].find_element(By.CSS_SELECTOR,'div[class="keytip"]').click()
time.sleep(1) 
keys[9].find_element(By.CSS_SELECTOR,'div[class="keytip"]').click()
time.sleep(1.4)
key_click(11)
time.sleep(0.3)
key_click(12)
time.sleep(0.6)
key_click2(14,10)
time.sleep(0.6)
key_click(15)
time.sleep(0.6)
key_click2(16,11)
time.sleep(0.6)
key_click(13)
time.sleep(0.6)
key_click2(14,9)
time.sleep(0.6)
key_click(11)
time.sleep(0.6)
key_click2(12,10)
time.sleep(0.6)
time.sleep(0.8)

keys[14].find_element(By.CSS_SELECTOR,'div[class="keytip"]').click()
keys[10].find_element(By.CSS_SELECTOR,'div[class="keytip"]').click()
time.sleep(0.3)
key_click(18)
time.sleep(0.3)
key_click(14)
time.sleep(0.3)
key_click(18)
time.sleep(0.3)
key_click(14)
time.sleep(0.8)
key_click(9)
time.sleep(0.8)
###########
key_click(14)
time.sleep(0.3)
key_click(18)
time.sleep(0.3)
key_click(14)
time.sleep(0.3)
key_click(18)
time.sleep(0.3)
key_click(14)
time.sleep(0.6)
####
keys[14].find_element(By.CSS_SELECTOR,'div[class="keytip"]').click()
keys[12].find_element(By.CSS_SELECTOR,'div[class="keytip"]').click()
time.sleep(0.4)
key_click(18)
time.sleep(0.3)
key_click(14)
time.sleep(0.3)
key_click(18)
time.sleep(0.3)
key_click(14)
time.sleep(0.8)
key_click(9)
time.sleep(0.8)

key_click(14)
time.sleep(0.3)
key_click(15)
time.sleep(0.3)
key_click(14)
time.sleep(0.3)
key_click(16)
time.sleep(0.3)
key_click(14)
time.sleep(0.9)

keys[14].find_element(By.CSS_SELECTOR,'div[class="keytip"]').click()
keys[10].find_element(By.CSS_SELECTOR,'div[class="keytip"]').click()
time.sleep(0.3)
key_click(18)
time.sleep(0.3)
key_click(14)
time.sleep(0.3)
key_click(18)
time.sleep(0.3)
key_click(14)
time.sleep(0.8)
key_click(9)
time.sleep(0.8)
###########
key_click(14)
time.sleep(0.3)
key_click(18)
time.sleep(0.3)
key_click(14)
time.sleep(0.3)
key_click(18)
time.sleep(0.3)
key_click(14)
time.sleep(0.6)
####
keys[14].find_element(By.CSS_SELECTOR,'div[class="keytip"]').click()
keys[12].find_element(By.CSS_SELECTOR,'div[class="keytip"]').click()
time.sleep(0.3)
key_click(18)
time.sleep(0.3)
key_click(14)
time.sleep(0.3)
key_click(18)
time.sleep(0.3)
key_click(14)
time.sleep(0.8)
key_click(9)
time.sleep(1)

key_click(14)
time.sleep(0.3)
key_click(21)
time.sleep(0.3)
key_click(20)
time.sleep(0.3)
key_click(19)
time.sleep(0.3)
key_click(16)
time.sleep(0.3)
key_click(18)
time.sleep(0.3)
key_click(13)

